name: hd2_app
description: Official app for HackDearborn 2.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player:
  curved_navigation_bar:
  
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  syncfusion_flutter_calendar: ^21.1.41
  dismissible_page: ^1.0.2
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
     - assets/
   
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   # min_sdk_android: 21 # android min sdk min:16, default 21