name: hd2_app
description: Official app for HackDearborn 2.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player:
  curved_navigation_bar:
  
  cupertino_icons: ^1.0.2
  dismissible_page: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
     - assets/
   
  # Can add custom fonts here