// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZxYZCTQnyic6Y9JkmjZgHoUPNXAqodE',
    appId: '1:974919363553:android:506c1e8365f767a36000a0',
    messagingSenderId: '974919363553',
    projectId: 'hckdbn',
    databaseURL: 'https://hckdbn-default-rtdb.firebaseio.com',
    storageBucket: 'hckdbn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDU6CCnUtkJxhZAqUI2XvsKufQeH15Wsk',
    appId: '1:974919363553:ios:9ca80f4e78389e3c6000a0',
    messagingSenderId: '974919363553',
    projectId: 'hckdbn',
    databaseURL: 'https://hckdbn-default-rtdb.firebaseio.com',
    storageBucket: 'hckdbn.appspot.com',
    iosClientId: '974919363553-lbi1ob691ls26rv3pmivj49967arbn8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.hd2App',
  );
}
